export default function handler(req, res) {

    const countryCapitalMap = {
        "afghanistan": "Kabul",
        "albania": "Tirana",
        "algeria": "Algiers",
        "andorra": "Andorra la Vella",
        "angola": "Luanda",
        "antigua and barbuda": "Saint John's",
        "argentina": "Buenos Aires",
        "armenia": "Yerevan",
        "australia": "Canberra",
        "austria": "Vienna",
        "azerbaijan": "Baku",
        "bahamas": "Nassau",
        "bahrain": "Manama",
        "bangladesh": "Dhaka",
        "barbados": "Bridgetown",
        "belarus": "Minsk",
        "belgium": "Brussels",
        "belize": "Belmopan",
        "benin": "Porto-Novo",
        "bhutan": "Thimphu",
        "bolivia": "Sucre",
        "bosnia and herzegovina": "Sarajevo",
        "botswana": "Gaborone",
        "brazil": "Brasília",
        "brunei": "Bandar Seri Begawan",
        "bulgaria": "Sofia",
        "burkina faso": "Ouagadougou",
        "burundi": "Gitega",
        "cabo verde": "Praia",
        "cambodia": "Phnom Penh",
        "cameroon": "Yaoundé",
        "canada": "Ottawa",
        "central african republic": "Bangui",
        "chad": "N'Djamena",
        "chile": "Santiago",
        "china": "Beijing",
        "colombia": "Bogotá",
        "comoros": "Moroni",
        "congo (congo-brazzaville)": "Brazzaville",
        "congo (democratic republic of the congo)": "Kinshasa",
        "congo dr": "Kinshasa",
        "costa rica": "San José",
        "croatia": "Zagreb",
        "cuba": "Havana",
        "cyprus": "Nicosia",
        "czechia (czech republic)": "Prague",
        "denmark": "Copenhagen",
        "djibouti": "Djibouti",
        "dominica": "Roseau",
        "dominican republic": "Santo Domingo",
        "dr congo": "Kinshasa",
        "ecuador": "Quito",
        "egypt": "Cairo",
        "el salvador": "San Salvador",
        "equatorial guinea": "Malabo",
        "eritrea": "Asmara",
        "estonia": "Tallinn",
        "eswatini (fmr. swaziland)": "Mbabane",
        "ethiopia": "Addis Ababa",
        "fiji": "Suva",
        "finland": "Helsinki",
        "france": "Paris",
        "gabon": "Libreville",
        "gambia": "Banjul",
        "georgia": "Tbilisi",
        "germany": "Berlin",
        "ghana": "Accra",
        "greece": "Athens",
        "grenada": "St. George's",
        "guatemala": "Guatemala City",
        "guinea": "Conakry",
        "guinea-bissau": "Bissau",
        "guyana": "Georgetown",
        "haiti": "Port-au-Prince",
        "honduras": "Tegucigalpa",
        "hungary": "Budapest",
        "iceland": "Reykjavik",
        "india": "New Delhi",
        "indonesia": "Jakarta",
        "iran": "Tehran",
        "iraq": "Baghdad",
        "ireland": "Dublin",
        "israel": "Jerusalem",
        "italy": "Rome",
        "jamaica": "Kingston",
        "japan": "Tokyo",
        "jordan": "Amman",
        "kazakhstan": "Nur-Sultan",
        "kenya": "Nairobi",
        "kiribati": "Tarawa Atoll",
        "korea (north)": "Pyongyang",
        "korea (south)": "Seoul",
        "kuwait": "Kuwait City",
        "kyrgyzstan": "Bishkek",
        "laos": "Vientiane",
        "latvia": "Riga",
        "lebanon": "Beirut",
        "lesotho": "Maseru",
        "liberia": "Monrovia",
        "libya": "Tripoli",
        "liechtenstein": "Vaduz",
        "lithuania": "Vilnius",
        "luxembourg": "Luxembourg City",
        "madagascar": "Antananarivo",
        "malawi": "Lilongwe",
        "malaysia": "Kuala Lumpur",
        "maldives": "Malé",
        "mali": "Bamako",
        "malta": "Valletta",
        "marshall islands": "Majuro",
        "mauritania": "Nouakchott",
        "mauritius": "Port Louis",
        "mexico": "Mexico City",
        "micronesia": "Palikir",
        "moldova": "Chisinau",
        "monaco": "Monaco",
        "mongolia": "Ulaanbaatar",
        "montenegro": "Podgorica",
        "morocco": "Rabat",
        "mozambique": "Maputo",
        "myanmar (formerly burma)": "Naypyidaw",
        "namibia": "Windhoek",
        "nauru": "Yaren",
        "nepal": "Kathmandu",
        "netherlands": "Amsterdam",
        "new zealand": "Wellington",
        "nicaragua": "Managua",
        "niger": "Niamey",
        "nigeria": "Abuja",
        "north macedonia (formerly macedonia)": "Skopje",
        "norway": "Oslo",
        "oman": "Muscat",
        "pakistan": "Islamabad",
        "palau": "Ngerulmud",
        "panama": "Panama City",
        "papua new guinea": "Port Moresby",
        "paraguay": "Asunción",
        "peru": "Lima",
        "philippines": "Manila",
        "poland": "Warsaw",
        "portugal": "Lisbon",
        "qatar": "Doha",
        "romania": "Bucharest",
        "russia": "Moscow",
        "rwanda": "Kigali",
        "saint kitts and nevis": "Basseterre",
        "saint lucia": "Castries",
        "saint vincent and the grenadines": "Kingstown",
        "samoa": "Apia",
        "san marino": "City of San Marino",
        "sao tome and principe": "São Tomé",
        "saudi arabia": "Riyadh",
        "senegal": "Dakar",
        "serbia": "Belgrade",
        "seychelles": "Victoria",
        "sierra leone": "Freetown",
        "singapore": "Singapore",
        "slovakia": "Bratislava",
        "slovenia": "Ljubljana",
        "solomon islands": "Honiara",
        "somalia": "Mogadishu",
        "south africa": "Pretoria",
        "south sudan": "Juba",
        "spain": "Madrid",
        "sri lanka": "Sri Jayawardenepura Kotte",
        "sudan": "Khartoum",
        "suriname": "Paramaribo",
        "sweden": "Stockholm",
        "switzerland": "Bern",
        "syria": "Damascus",
        "taiwan": "Taipei",
        "tajikistan": "Dushanbe",
        "tanzania": "Dodoma",
        "thailand": "Bangkok",
        "timor-leste": "Dili",
        "togo": "Lomé",
        "tonga": "Nukuʻalofa",
        "trinidad and tobago": "Port of Spain",
        "tunisia": "Tunis",
        "turkey": "Ankara",
        "turkmenistan": "Ashgabat",
        "tuvalu": "Funafuti",
        "uganda": "Kampala",
        "ukraine": "Kyiv",
        "united arab emirates": "Abu Dhabi",
        "united kingdom": "London",
        "united states": "Washington, D.C.",
        "uruguay": "Montevideo",
        "uzbekistan": "Tashkent",
        "vanuatu": "Port Vila",
        "vatican city": "Vatican City",
        "venezuela": "Caracas",
        "vietnam": "Hanoi",
        "yemen": "Sanaa",
        "zambia": "Lusaka",
        "zimbabwe": "Harare"
    };

    if (req.method === 'POST') {
        const { input } = req.body;

        if (!input) {
            return res.status(400).json({ error: 'Country is required' });
        }

        const capital = countryCapitalMap[input.toLowerCase()];

        if (!capital) {
            return res.status(404).json({ error: `Capital not found for country: ${input}` });
        }

        return res.json({ input, capital });
    } else if (req.method === 'GET') {
        return res.json({
            name: "getCapital",
            description: "Returns the capital of a given country",
            input: {
                type: "string",
                example: "United Kingdom"
            },
            output: {
                type: "string",
                example: "London"
            }
        });
    } else {
        return res.status(405).json({ error: 'Method not allowed. Use POST to get the capital or GET for documentation.' });
    }

}
